### PR TITLE
pubkey unit tests

### PR DESCRIPTION
**Pull request by littleskunk**

### CODE REVIEW

**Comment by littleskunk** [comment]
The last 2 pubkey unit tests should expect an error message but at the moment they do not. -> https://github.com/Storj/bridge/issues/53

**Comment by gordonwritescode** [comment]
@littleskunk is this good to go?

**Comment by littleskunk** [comment]
@gordonwritescode now it is fine :)

**Comment by gordonwritescode** [comment]
:ship:

**Pull request merged**
