### PR TITLE
Add analytics to user events

### PR DESCRIPTION
**Pull request by frdwrd**
Add Segment, and events for certain user actions.

Depends on https://github.com/Storj/service-storage-models/pull/89
Depends on deployment of https://github.com/Storj/uuid-mailer

**General**:
- [X] Identify user on signup
- [x] Obfuscate identifiable info
- [x] Respect DNT headers
- [x] Figure out emails
- [x] Add `{uuid}@user.storj.io` to the identify code
- [x] Move segment write key to config.js
- [x] Break out analytics into its own package.
- [x] storj-analytics published
- [x] service-storage models v8.15.0 published
- [x] Bump service models requirement to 8.15.0

**Events**:
- [X] signup
- [X] user activation
- [X] Upload Rate Limiting
- [X] Download Rate Limiting
- [x] Bucket Created/Destroyed
- [x] Token generated
- [x] File upload started
- [x] File upload completed
- [x] File pointers retreived
- [x] Key registered/destroyed

**Testing**:
- [x] Figure out how to test analytics.js
- [X] Stub out analytics in tests 
- [x] Fix Travis

### CODE REVIEW

**Comment by frdwrd** [comment]
Need env variable set for SEGMENT_WRITE_KEY @phutchins

**Comment by phutchins** [comment]
@frdwrd can work with you to get this set up. Lets look at why test coverage decreased so drastically and the tests...

**Comment by frdwrd** [comment]
Tests are failing because Travis needs a `SEGMENT_WRITE_KEY` env variable

**Comment by frdwrd** [comment]
Now dependent on https://github.com/Storj/service-storage-models/pull/89

**Comment by frdwrd** [comment]
This is ready for staging as soon as the new service-storage-models is deployed.

**Pull request merged**
