### PR TITLE
Add rabbitmq vagrant dependency

### PR DESCRIPTION
**Pull request by bryanchriswhite**
@niahmiah,@gordon: I was trying to run the latest version of bridge (v0.9.3) and noticed some things changed; subsequently, Shawn helped me locate #117.

I added rabbitmq to the ansible playbook for vagrant so it will be installed, set to run on boot and ensured running after provisioning is finished.

When trying to run `NODE_ENV=develop storj-bridge`, I noticed some missing dependencies so I added them in 0cc9301 but am not sure that they are all proper deps and not dev-deps so please correct any mistakes there.

It seems that there's still something that I'm not aware of that is required to get this version of bridge up and running so I will wait for #117 👍 .

In the mean time though I thought I'd provide the console output from my current attempts to run `NODE_ENV=develop storj-bridge` (or `npm run develop`), in case something else is wrong with my setup (like maybe a dep version mismatch or something):

_(NOTE: rabbitmq lines removed for brevity)_
```bash
/vagrant/node_modules/storj/node_modules/bitcore-lib/lib/crypto/point.js:112
    throw new Error('Invalid y value for curve.');
    ^

Error: Invalid y value for curve.
    at Point.validate (/vagrant/node_modules/storj/node_modules/bitcore-lib/lib/crypto/point.js:112:11)
    at new PublicKey (/vagrant/node_modules/storj/node_modules/bitcore-lib/lib/publickey.js:53:14)
    at Function.PublicKey.fromPrivateKey (/vagrant/node_modules/storj/node_modules/bitcore-lib/lib/publickey.js:221:10)
    at PrivateKey.toPublicKey (/vagrant/node_modules/storj/node_modules/bitcore-lib/lib/privatekey.js:349:30)
    at new KeyPair (/vagrant/node_modules/storj/lib/keypair.js:26:32)
    at Object.KeyPair (/vagrant/node_modules/storj/lib/keypair.js:17:12)
    at Object.<anonymous> (/vagrant/bin/minion.js:19:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

### CODE REVIEW

**Comment by bryanchriswhite** [comment]
So it looks like it's `bitcore-lib` that has the dependency issue (through `storj`). But that's strange because when I `npm install`ed I got v0.13.16. And you can see these deps in it's [package.json](https://github.com/bitpay/bitcore-lib/blob/v0.13.16/package.json#L82) (I verified that my copy's package.json looks the same).

@bookchin thoughts?

#### Errors:
```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ NODE_ENV=develop storj-bridge
module.js:327
    throw err;
    ^

Error: Cannot find module 'bn.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/vagrant/node_modules/storj/node_modules/bitcore-lib/lib/crypto/bn.js:3:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```
```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ NODE_ENV=develop storj-bridge
module.js:327
    throw err;
    ^

Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/vagrant/node_modules/storj/node_modules/bitcore-lib/lib/errors/index.js:3:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
      at require (internal/module.js:12:17)
```
```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ NODE_ENV=develop storj-bridge
module.js:327
    throw err;
    ^

Error: Cannot find module 'bs58'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/vagrant/node_modules/storj/node_modules/bitcore-lib/lib/encoding/base58.js:4:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
```
```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ NODE_ENV=develop storj-bridge
module.js:327
    throw err;
    ^

Error: Cannot find module 'inherits'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/vagrant/node_modules/storj/node_modules/bitcore-lib/lib/transaction/input/publickey.js:3:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
          at require (internal/module.js:12:17)
```

**Comment by bryanchriswhite** [comment]
I did an `npm install storj` to see what bitcore-lib deps are pulled down:

```
...
├── bitcore-lib@0.13.16 (inherits@2.0.1, buffer-compare@1.0.0, bs58@2.0.0, bn.js@2.0.4, elliptic@3.0.3, lodash@3.10.1)
...
```

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ ls node_modules/storj/node_modules/bitcore-lib/node_modules/
bn.js  bs58  buffer-compare  elliptic  inherits  lodash
```

But when I `npm install` in the bridge root, `~/storj/~/bitcore-lib` doesn't have a node_modules directory:

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ ls node_modules/storj/node_modules/bitcore-lib
benchmark           bitcore-lib.min.js      CONTRIBUTING.md  index.js       LICENSE              README.md
bitcore-lib.js      bitcore-lib.min.js.sig  docs             karma.conf.js  npm-shrinkwrap.json  test
bitcore-lib.js.sig  bower.json              gulpfile.js      lib            package.json
```

**Comment by bryanchriswhite** [comment]
Further, I did an `npm ls bn.js bs58 inherits lodash elliptic` to check if there were other versions of those deps installed that may be causing issues:

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ npm ls bn.js bs58 inherits lodash elliptic
npm WARN unmet dependency /vagrant/node_modules/storj/node_modules/bitcore-lib requires elliptic@'=3.0.3' but will load
npm WARN unmet dependency /vagrant/node_modules/elliptic,
npm WARN unmet dependency which is version 6.3.1
npm WARN unmet dependency /vagrant/node_modules/jsdoc/node_modules/catharsis/node_modules/underscore-contrib requires underscore@'1.6.0' but will load
npm WARN unmet dependency /vagrant/node_modules/jsdoc/node_modules/underscore,
npm WARN unmet dependency which is version 1.8.3
storj-bridge@0.9.3 /vagrant
├─┬ amqplib@0.4.2
│ └─┬ readable-stream@1.1.14
│   └── inherits@2.0.1
├─┬ concat-stream@1.5.1
│ └── inherits@2.0.1
├─┬ coveralls@2.11.9
│ └─┬ request@2.67.0
│   └─┬ bl@1.0.3
│     └─┬ readable-stream@2.0.6
│       └── inherits@2.0.1
├─┬ elliptic@6.3.1  invalid
│ ├── bn.js@4.11.4
│ └── inherits@2.0.1
├─┬ express@4.14.0
│ └─┬ send@0.14.1
│   └─┬ http-errors@1.5.0
│     └── inherits@2.0.1
├─┬ ink-docstrap@1.2.1
│ └─┬ sanitize-html@1.12.0
│   └─┬ htmlparser2@3.9.1
│     └── inherits@2.0.1
├─┬ istanbul@0.4.4
│ └─┬ fileset@0.2.1
│   └─┬ glob@5.0.15
│     └── inherits@2.0.1
├─┬ jshint@2.8.0
│ ├─┬ cli@0.6.6
│ │ └─┬ glob@3.2.11
│ │   └── inherits@2.0.1
│ ├─┬ htmlparser2@3.8.3
│ │ └─┬ readable-stream@1.1.14
│ │   └── inherits@2.0.1
│ └── lodash@3.7.0
├─┬ memdown@1.2.0
│ └── inherits@2.0.1
├─┬ mocha@2.5.3
│ └─┬ glob@3.2.11
│   └── inherits@2.0.1
├─┬ mongoose@4.5.2
│ └─┬ mongodb@2.1.18
│   └─┬ readable-stream@1.0.31
│     └── inherits@2.0.1
├─┬ readable-stream@2.1.4
│ └── inherits@2.0.1
├─┬ sinon@1.17.4
│ └─┬ util@0.10.3
│   └── inherits@2.0.1
└─┬ storj@1.3.2
  ├─┬ kad@1.5.15
  │ └── lodash@3.10.1
  ├─┬ levelup@1.3.2
  │ └─┬ level-iterator-stream@1.3.1
  │   └── inherits@2.0.1
  ├─┬ prompt@1.0.0
  │ └─┬ utile@0.3.0
  │   └─┬ rimraf@2.5.2
  │     └─┬ glob@7.0.5
  │       └── inherits@2.0.1
  └─┬ request@2.72.0
    └─┬ bl@1.1.2
      └─┬ readable-stream@2.0.6
        └── inherits@2.0.1

npm ERR! invalid: elliptic@6.3.1 /vagrant/node_modules/elliptic
```

Could elliptic be causing a conflict, preventing bitcore-lib from finishing it's install?

I would hypothesise that on a machine with a working intall of bridge at v0.9.3 or higher, if you `rm -rf node_modules` and `npm i` you'll have the same issue.

For now I'll drop the package.json commit.

**Comment by bookchin** [comment]
What version of Node and NPM are you running? Should be LTS (4.x.x).

**Comment by bryanchriswhite** [comment]
```
npm WARN engine storj@1.3.2: wanted: {"node":"^4.4.4"} (current: {"node":"4.4.3","npm":"2.15.1"})
```

**Comment by bookchin** [comment]
Hm. Install working fine on Debian 8:

```
gordon@gordonhall ~/Code/storj-bridge                                                                                                                                                                                               [12:35:50] 
> $ git pull upstream master                                                                                                                                                                                               ⬡ 4.4.3 [±master ✓]
From github.com:Storj/bridge
 * branch            master     -> FETCH_HEAD
Already up-to-date.
                                                                                                                                                                                                                                               
gordon@gordonhall ~/Code/storj-bridge                                                                                                                                                                                               [12:35:59] 
> $ rm -rf node_modules                                                                                                                                                                                                    ⬡ 4.4.3 [±master ✓]
                                                                                                                                                                                                                                               
gordon@gordonhall ~/Code/storj-bridge                                                                                                                                                                                               [12:36:02] 
> $ npm install                                                                                                                                                                                                            ⬡ 4.4.3 [±master ✓]
npm WARN engine storj@1.3.2: wanted: {"node":"^4.4.4"} (current: {"node":"4.4.3","npm":"2.15.1"})
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
-
> leveldown@1.4.6 install /home/gordon/Code/storj-bridge/node_modules/storj/node_modules/leveldown
> prebuild --install

basic-auth@1.0.4 node_modules/basic-auth

ms@0.7.1 node_modules/ms

merge@1.2.0 node_modules/merge

mime-db@1.23.0 node_modules/mime-db

kad-logger-json@0.1.2 node_modules/kad-logger-json

hat@0.0.3 node_modules/hat

async@1.5.2 node_modules/async

through@2.3.8 node_modules/through

cors@2.7.1 node_modules/cors
└── vary@1.1.0

readable-stream@2.1.4 node_modules/readable-stream
├── buffer-shims@1.0.0
├── string_decoder@0.10.31
├── inherits@2.0.1
├── util-deprecate@1.0.2
├── process-nextick-args@1.0.7
├── core-util-is@1.0.2
└── isarray@1.0.0

mongoose-types@1.0.3 node_modules/mongoose-types

elliptic@6.3.1 node_modules/elliptic
├── brorand@1.0.5
├── inherits@2.0.1
├── hash.js@1.0.3
└── bn.js@4.11.4

concat-stream@1.5.1 node_modules/concat-stream
├── inherits@2.0.1
├── typedarray@0.0.6
└── readable-stream@2.0.6 (string_decoder@0.10.31, process-nextick-args@1.0.7, util-deprecate@1.0.2, core-util-is@1.0.2, isarray@1.0.0)

noisegen@1.0.0 node_modules/noisegen
└── commander@2.9.0 (graceful-readlink@1.0.1)

memdown@1.2.0 node_modules/memdown
├── inherits@2.0.1
├── ltgt@1.0.2
├── functional-red-black-tree@1.0.1
└── abstract-leveldown@2.6.0 (xtend@4.0.1)

chai@3.5.0 node_modules/chai
├── assertion-error@1.0.2
├── type-detect@1.0.0
└── deep-eql@0.1.3 (type-detect@0.1.1)

express@4.14.0 node_modules/express
├── escape-html@1.0.3
├── array-flatten@1.1.1
├── utils-merge@1.0.0
├── merge-descriptors@1.0.1
├── methods@1.1.2
├── content-type@1.0.2
├── vary@1.1.0
├── etag@1.7.0
├── fresh@0.3.0
├── content-disposition@0.5.1
├── parseurl@1.3.1
├── cookie-signature@1.0.6
├── encodeurl@1.0.1
├── range-parser@1.2.0
├── path-to-regexp@0.1.7
├── cookie@0.3.1
├── serve-static@1.11.1
├── depd@1.1.0
├── debug@2.2.0
├── qs@6.2.0
├── on-finished@2.3.0 (ee-first@1.1.1)
├── type-is@1.6.13 (media-typer@0.3.0, mime-types@2.1.11)
├── finalhandler@0.5.0 (unpipe@1.0.0, statuses@1.3.0)
├── accepts@1.3.3 (mime-types@2.1.11, negotiator@0.6.1)
├── proxy-addr@1.1.2 (forwarded@0.1.0, ipaddr.js@1.1.1)
└── send@0.14.1 (destroy@1.0.4, statuses@1.3.0, mime@1.3.4, http-errors@1.5.0)

nodemailer@2.4.2 node_modules/nodemailer
├── socks@1.1.9 (ip@1.1.3, smart-buffer@1.0.11)
├── nodemailer-shared@1.0.5 (nodemailer-fetch@1.4.0)
├── mailcomposer@3.9.0 (buildmail@3.7.0)
├── libmime@2.0.3 (libqp@1.1.0, libbase64@0.1.0, iconv-lite@0.4.13)
├── nodemailer-direct-transport@3.1.0 (smtp-connection@2.5.0)
├── nodemailer-smtp-transport@2.5.0 (nodemailer-wellknown@0.1.9, smtp-connection@2.5.0)
└── nodemailer-smtp-pool@2.6.0 (nodemailer-wellknown@0.1.9, smtp-connection@2.5.0)

sinon@1.17.4 node_modules/sinon
├── formatio@1.1.1
├── samsam@1.1.2
├── lolex@1.3.2
└── util@0.10.3 (inherits@2.0.1)

amqplib@0.4.2 node_modules/amqplib
├── buffer-more-ints@0.0.2
├── bitsyntax@0.0.4
├── readable-stream@1.1.14 (string_decoder@0.10.31, isarray@0.0.1, inherits@2.0.1, core-util-is@1.0.2)
└── when@3.6.4

proxyquire@1.7.9 node_modules/proxyquire
├── module-not-found-error@1.0.1
├── fill-keys@1.0.2 (merge-descriptors@1.0.1, is-object@1.0.1)
└── resolve@1.1.7

mocha@2.5.3 node_modules/mocha
├── escape-string-regexp@1.0.2
├── commander@2.3.0
├── diff@1.4.0
├── supports-color@1.2.0
├── growl@1.9.2
├── to-iso-string@0.0.2
├── debug@2.2.0
├── mkdirp@0.5.1 (minimist@0.0.8)
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
└── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)

istanbul@0.4.4 node_modules/istanbul
├── abbrev@1.0.9
├── wordwrap@1.0.0
├── nopt@3.0.6
├── esprima@2.7.2
├── supports-color@3.1.2 (has-flag@1.0.0)
├── once@1.3.3 (wrappy@1.0.2)
├── which@1.2.10 (isexe@1.1.2)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── fileset@0.2.1 (minimatch@2.0.10, glob@5.0.15)
├── resolve@1.1.7
├── escodegen@1.8.0 (estraverse@1.9.3, esutils@2.0.2, optionator@0.8.1, source-map@0.2.0)
└── js-yaml@3.6.1 (argparse@1.0.7)

coveralls@2.11.9 node_modules/coveralls
├── lcov-parse@0.0.6
├── log-driver@1.2.4
├── minimist@1.2.0
├── js-yaml@3.0.1 (esprima@1.0.4, argparse@0.1.16)
└── request@2.67.0 (aws-sign2@0.6.0, tunnel-agent@0.4.3, oauth-sign@0.8.2, forever-agent@0.6.1, caseless@0.11.0, mime-types@2.1.11, is-typedarray@1.0.0, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, form-data@1.0.0-rc4, tough-cookie@2.2.2, node-uuid@1.4.7, qs@5.2.0, combined-stream@1.0.5, bl@1.0.3, hawk@3.1.3, http-signature@1.1.1, har-validator@2.0.6)

mongoose@4.5.2 node_modules/mongoose
├── sliced@1.0.1
├── hooks-fixed@1.1.0
├── regexp-clone@0.0.1
├── muri@1.1.0
├── mpromise@0.5.5
├── mpath@0.2.1
├── kareem@1.1.0
├── bson@0.4.23
├── mquery@1.11.0 (debug@2.2.0, sliced@0.0.5, bluebird@2.10.2)
└── mongodb@2.1.18 (es6-promise@3.0.2, readable-stream@1.0.31, mongodb-core@1.3.18)

handlebars@4.0.5 node_modules/handlebars
├── source-map@0.4.4 (amdefine@1.0.0)
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
└── uglify-js@2.6.4 (async@0.2.10, uglify-to-browserify@1.0.2, source-map@0.5.6, yargs@3.10.0)

jsdoc@3.4.0 node_modules/jsdoc
├── escape-string-regexp@1.0.5
├── async@1.4.2
├── taffydb@2.6.2
├── strip-json-comments@1.0.4
├── underscore@1.8.3
├── marked@0.3.5
├── wrench@1.5.9
├── js2xmlparser@1.0.0
├── espree@2.2.5
├── requizzle@0.2.1 (underscore@1.6.0)
├── bluebird@2.9.34
└── catharsis@0.8.8 (underscore-contrib@0.3.0)

jshint@2.8.0 node_modules/jshint
├── strip-json-comments@1.0.4
├── exit@0.1.2
├── console-browserify@1.1.0 (date-now@0.1.4)
├── shelljs@0.3.0
├── minimatch@2.0.10 (brace-expansion@1.1.5)
├── cli@0.6.6 (glob@3.2.11)
├── htmlparser2@3.8.3 (domelementtype@1.3.0, entities@1.0.0, domhandler@2.3.0, readable-stream@1.1.14, domutils@1.5.1)
└── lodash@3.7.0

ink-docstrap@1.2.1 node_modules/ink-docstrap
├── sanitize-html@1.12.0 (regexp-quote@0.0.0, xtend@4.0.1, htmlparser2@3.9.1)
└── moment@2.13.0

storj@1.3.2 node_modules/storj
├── knuth-shuffle@1.0.1
├── ip@1.1.3
├── mtree@0.0.1
├── mime@1.3.4
├── bitcore-message@1.0.2
├── node-uuid@1.4.7
├── semver@5.1.1
├── colors@1.1.2
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── json-stable-stringify@1.0.1 (jsonify@0.0.0)
├── bitcore-ecies@1.0.1 (aes@0.1.0)
├── tmp@0.0.28 (os-tmpdir@1.0.1)
├── ws@1.1.1 (options@0.0.6, ultron@1.0.2)
├── jsen@0.6.1
├── kad-quasar@0.1.3 (bloem@0.2.4)
├── portfinder@1.0.3 (mkdirp@0.5.1)
├── nat-upnp@1.0.2 (ip@0.0.5, async@0.1.22, xml2js@0.1.14, request@2.10.0)
├── levelup@1.3.2 (prr@1.0.1, xtend@4.0.1, level-codec@6.1.0, level-errors@1.0.4, deferred-leveldown@1.2.1, level-iterator-stream@1.3.1)
├── request@2.72.0 (tunnel-agent@0.4.3, aws-sign2@0.6.0, forever-agent@0.6.1, oauth-sign@0.8.2, mime-types@2.1.11, is-typedarray@1.0.0, caseless@0.11.0, stringstream@0.0.5, aws4@1.4.1, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, form-data@1.0.0-rc4, tough-cookie@2.2.2, qs@6.1.0, combined-stream@1.0.5, hawk@3.1.3, bl@1.1.2, http-signature@1.1.1, har-validator@2.0.6)
├── prompt@1.0.0 (revalidator@0.1.8, pkginfo@0.4.0, read@1.0.7, winston@2.1.1, utile@0.3.0)
├── kad@1.5.15 (kad-fs@0.0.4, kad-memstore@0.0.1, async@0.9.2, kad-localstorage@0.0.7, lodash@3.10.1, clarinet@0.11.0)
├── bitcore-lib@0.13.16 (buffer-compare@1.0.0, inherits@2.0.1, bs58@2.0.0, bn.js@2.0.4, elliptic@3.0.3, lodash@3.10.1)
└── leveldown@1.4.6 (bindings@1.2.1, fast-future@1.0.1, nan@2.3.5, abstract-leveldown@2.4.1, prebuild@4.2.2)
```

**Comment by bryanchriswhite** [comment]
That's really weird. The machine in question is running Ubuntu 14.04.

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ uname -a
Linux vagrant-ubuntu-trusty-64 3.13.0-53-generic #89-Ubuntu SMP Wed May 20 10:34:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

First `npm i`:
```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ npm i
npm WARN engine storj@1.3.2: wanted: {"node":"^4.4.4"} (current: {"node":"4.4.3","npm":"2.15.1"})
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
Killed
```

Second `npm i`:
```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ npm i
npm WARN unmet dependency /vagrant/node_modules/storj/node_modules/bitcore-lib requires elliptic@'=3.0.3' but will load
npm WARN unmet dependency /vagrant/node_modules/elliptic,
npm WARN unmet dependency which is version 6.3.1
npm WARN unmet dependency /vagrant/node_modules/jsdoc/node_modules/catharsis/node_modules/underscore-contrib requires underscore@'1.6.0' but will load
npm WARN unmet dependency /vagrant/node_modules/jsdoc/node_modules/underscore,
npm WARN unmet dependency which is version 1.8.3
```

**Comment by bryanchriswhite** [comment]
@bookchin fwiw a `vagrant destroy && vagrant up` solved my problem... not sure what was up but it probably has to do with global mutable state :p

**Pull request merged**
