### PR TITLE
Dockerize the storj-monitor project and create a build script to assist in building, pushing and other related tasks

### PR DESCRIPTION
**Pull request by phutchins**

### CODE REVIEW

**Comment by braydonf** [comment]
Can we put all of these in a `contrib` directory?

**Comment by phutchins** [comment]
A contrib directory doesn't make sense for what these are. The accepted pattern is a single Dockerfile or a directory named dockerfiles which contains dockerfiles named appropriately for each action.

The build script belongs in the top level so it can be easily discovered. It may not end up living in this repository however and I will probably move it to the storj-base repo which will subtree all of our other projects.

**Comment by braydonf** [comment]
Closing since I think this has moved to another repo.

**Comment by braydonf** [comment]
I don't think that docker files should exist at a higher level project that combines all of the pieces together, and all of the docker files and build scripts can be together where work on that code is shared and updates to them does not require making edits to many different repositories.

**Comment by phutchins** [comment]
I agree that the build script should (and does already) live at a higher level. However, I feel that the Dockerfiles belong with the repo as they have multiple uses and should change with the codebase as the codebase changes for a particular service. Putting the dockerfiles in a separate place at the moment complicates concerns as well as the build process.

The generally accepted pattern is to have a Dockerfile at the root of a project. When you have a reason to have multiple dockerfiles, you create a dockerfiles directory with the dockerfiles in it and call them as needed. We need to do that in our case due to the fact that we have two services being built from this. We could in the future make a single Dockerfile that is dynamic but I'm going to save that for a later date.

**Pull request merged**
