### PR TITLE
Implement SIP6

### PR DESCRIPTION
**Pull request by braydonf**
Implements https://github.com/Storj/sips/blob/master/sip-0006.md

Part of: https://github.com/Storj/integration/pull/5

### CODE REVIEW

**Comment by unicrus** [comment]
Didn't find other place to comment the proposal.

Even if prioritization of farmers that are geographically closer to the user can improve current state it's not so good generally. Geographical nearness is not equal to network nearness. Host may be far away but have high-speed connection to Internet backbone. Prioritization based on shard transfer speed looks much better.

**Comment by braydonf** [comment]
@unicrus Yes, that's been discussed. We need a way to transform exchange reports into a metric for each farmer, so that we can start using that.

**Comment by aleitner** [comment]
Initial difficulty is too hard. None of my farmers can join the network

**Comment by braydonf** [comment]
Okay, added a method to initialize the settings.

**Comment by aleitner** [comment]
Init on redis start looks good

**Comment by braydonf** [comment]
Cool, added tests to make sure that those init values will be adjusted as expected, and added config options for farmer selection settings *(no longer constants)*.

**Pull request merged**
