### PR TITLE
[WIP] Testing: e2e plus...

### PR DESCRIPTION
**Pull request by bryanchriswhite**
### Abstract

In this PR I'd like to propose some changes in testing strategy to allow for more robust and isolated e2e (end-to-end) tests as well as adding unit tests and testing strategy for the currently uncovered express controller code.

### E2E Tests

I  suggest using the term "e2e" (end-to-end) rather than "integration". e2e is shorter and if we're going to stick with the file naming convention of `<module>.<test type>.js`, `users.integration.js`, etc. is going to get tedious after a while.

More importantly though, I feel that "end-to-end" carries more ubiquitous meaning than "integration". In the context of an express HTTP API, integration could refer to integration between any of the following: controller-model, model-DB, controller-model-view, controller-model-DB, etc. End-to-end refers to the entry point of the app from the perspective of consumers/clients (HTTP) all the way down to the persistence layer (DB). This requires that an e2e test exercise the router/controller (sometimes the same, sometimes not), model, db (including validations, etc).

### E2E Methodology

To properly exercise an application end-to-end the system under test should be running under normal circumstances, i.e., started in the say way and from the same point of execution as it would be in production. It may obviously may make some configuration changes while running in the test environment (connect to a test database, change the log level).

Each test should start from the perspective of a stable, external consumer/client. In the case of an express HTTP API under test this could be node's vanilla `http.request` or something like [superagent](https://github.com/visionmedia/superagent). The test should make assertions about the response but it should also make assertions about any side-effects that may be the result of a request. This may mean verifying that records have been added or updated in the database; the other end.

_obviously, not all requests will produce side-effects such that they require assertions be made against the DB but the point is that the application is being exercised all the way to that end if applicable_

Finally, it is sometimes necessary to setup a scenario and since **all tests should be done in an isolated environment from one another** we should not rely on any code from the system under test to produce those conditions. Instead, we may use fixture data or factories to provide the desired application state so the test can be performed consistently and without risk of failure of another component leaking into the test in question.

### Red-Green-Refactor

Generally speaking, I'm a BDD fan, as such I recommend writing tests **before** code **and running them to make sure they fail for the right reason(s)**. This helps reduce the likelihood of false-positives as well as encourages writing the minimal amount of code required to get the tests to pass. If you find that you can get away with writing stupid code, e.g., using string literals instead of a function call, then you probably need more coverage [(keep in mind things like spies are available)](http://sinonjs.org/). Finally, this approach forces you to think about the interface or process you're building and what is truly required to achieve the goal (which is defined by the tests).

Whenever adding tests to existing code it is recommended that you intentionally break the code under test, run the tests to make sure they fail because of the change you made. Then repair the code and ensure the tests pass again.

### CODE REVIEW

**Comment by bryanchriswhite** [comment]
NOTE: this PR branch is upstream from #138

**Comment by bryanchriswhite** [comment]
## CAUTION:
a7b8057 adds database-cleaner which currently **will delete all collections. DO NOT `npm test` WITHOUT BACKING UP DATA YOU CARE ABOUT**

**Comment by super3** [comment]
Will close #84

**Comment by bookchin** [comment]
@bryanchriswhite this looks dead, so I'm closing it. If I am wrong, just reopen it.

**Pull request closed without merging**
