### PR TITLE
billing-5: Automated billing features and Stripe integration

### PR DESCRIPTION
**Pull request by dylanlott**
Work In Progress Pull Request; 
- GraphQL implementation 
- New Credit and Debit models 
- /credits and /debits endpoints 
- Stripe integration 

TO DO:
- e2e tests 
- Front end form validation 
- Finish unit testing 
- Testing on staging

### CODE REVIEW

**Comment by dylanlott** [comment]
COMPLETD: 
- Credit card form validation 
- Bridge unit tests for `Credit` and `Debit`
- Billing Documentation for Ryan to use when creating abacus integration

TODO: 
- Add GBh and GB amounts on debits to track actual usage and not billed usage 
- Update `/debits` endpoint to handle sending GBh and GB amounts from abacus 
- Add expiration date handling for `promo_credit`

**Comment by dylanlott** [comment]
We're in the process of writing tests right now. As soon as Gordon's changes are ready, we're gonna start breaking our billing code out of bridge to fit with Gordon's new modular bridge approach. 

TODO: 
- Merge with Gordon's changes for Bridge
- Write full integration tests 
- Get billing features onto staging and test

**Comment by dylanlott** [comment]
Today I pulled all the billing code out of Bridge and put it into it's own repo and service called `billing` 

TODO: 
- Need to thoroughly test the `billing` service
- Need to add Bryan's test suite into `billing`
- Bring unit tests from bridge into `billing`

**Comment by bookchin** [comment]
Is this stale and closeable?

**Comment by dylanlott** [comment]
Closing pull request, all this work is going into the billing microservice and storj-service-storage-models now.

**Pull request closed without merging**
